"""
===============================================================================
SBER AI Journey — 3D Mesh Quality Control: Ablation Runner [v7.3]
===============================================================================
Phase 7 Config Versioning & Ablation Framework. Sequentially runs model configurations,
parses CV fold metrics, computes statistical significance (paired t-test),
and generates a comparative Markdown report.
===============================================================================
"""
import os
import json
import subprocess
import numpy as np
from scipy import stats

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_WORKSPACE_DIR = os.path.dirname(_SCRIPT_DIR)

def run_training(config_path: str, smoke_test: bool = True) -> dict:
    """Run pipeline training using specified config YAML file."""
    # Ensure config path is absolute or resolved relative to workspace
    if not os.path.isabs(config_path):
        resolved_config = os.path.join(_WORKSPACE_DIR, config_path)
    else:
        resolved_config = config_path

    cmd = ["python", os.path.join(_SCRIPT_DIR, "main.py"), "--mode", "train", "--config", resolved_config]
    if smoke_test:
        cmd.append("--smoke-test")
        
    print(f"\n[Ablation] Executing training: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)
    
    # Read metrics
    cv_results_path = os.path.join(_WORKSPACE_DIR, "logs", "cv_results.json")
    if os.path.exists(cv_results_path):
        with open(cv_results_path, "r") as f:
            return json.load(f)
    else:
        raise FileNotFoundError(f"cv_results.json not found at: {cv_results_path}")

def run_ablation_study():
    print("[Ablation] Starting comparative Ablation Study...")
    
    # Run Baseline config (late average)
    baseline_res = run_training("solution/configs/baseline.yaml", smoke_test=True)
    
    # Run Gated Fusion config
    gated_res = run_training("solution/configs/gated_fusion.yaml", smoke_test=True)
    
    # Extract fold final F1 scores
    baseline_scores = [fold["final_metrics"]["f1_final"] for fold in baseline_res["fold_results"]]
    gated_scores = [fold["final_metrics"]["f1_final"] for fold in gated_res["fold_results"]]
    
    # Extract subclass scores
    baseline_q = [fold["final_metrics"]["f1_quality"] for fold in baseline_res["fold_results"]]
    gated_q = [fold["final_metrics"]["f1_quality"] for fold in gated_res["fold_results"]]
    baseline_d = [fold["final_metrics"]["f1_defects"] for fold in baseline_res["fold_results"]]
    gated_d = [fold["final_metrics"]["f1_defects"] for fold in gated_res["fold_results"]]
    
    # Compute statistical significance
    # Paired t-test
    t_stat, p_val = stats.ttest_rel(gated_scores, baseline_scores)
    # Wilcoxon signed-rank test
    try:
        w_stat, w_p_val = stats.wilcoxon(gated_scores, baseline_scores)
    except Exception:
        w_p_val = 1.0  # fallback if all values are equal
        
    # Generate markdown report
    report = f"""# SBER 3D Mesh QC Ablation Study Report

Comparative analysis of visual-geometric modality fusion methods.

## Summary table

| Configuration | F1_final (Mean +/- Std) | F1_quality (Mean) | F1_defects (Mean) |
|---|---|---|---|
| **Baseline (Late Average)** | {np.mean(baseline_scores):.4f} +/- {np.std(baseline_scores):.4f} | {np.mean(baseline_q):.4f} | {np.mean(baseline_d):.4f} |
| **Gated Modality Fusion** | {np.mean(gated_scores):.4f} +/- {np.std(gated_scores):.4f} | {np.mean(gated_q):.4f} | {np.mean(gated_d):.4f} |

## Statistical Significance (F1_final)

* **Paired t-test:** t-statistic = {t_stat:.4f}, p-value = {p_val:.4f}
* **Wilcoxon signed-rank test:** p-value = {w_p_val:.4f}

{"*The difference is statistically significant (p < 0.05).*" if p_val < 0.05 else "*The difference is not statistically significant (p >= 0.05) under the smoke-test regime.*"}

---
Generated by Ablation Runner v7.3.
"""
    
    report_path = os.path.join(_WORKSPACE_DIR, "logs", "ablation_study_report.md")
    with open(report_path, "w") as f:
        f.write(report)
        
    print(f"\n[Ablation Complete] Report saved to: {report_path}")
    print(report)

if __name__ == "__main__":
    run_ablation_study()
